# Generated by Django 2.2.1 on 2019-06-12 03:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passionProjectApp', '0005_auto_20190611_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='realquestion',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='question_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realquestion',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='question_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 3, 19, 43, 585869)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 3, 19, 43, 585850)),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 3, 19, 43, 586498)),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 3, 19, 43, 586470)),
        ),
        migrations.AlterField(
            model_name='realquestion',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 3, 19, 43, 583422)),
        ),
        migrations.AlterField(
            model_name='realquestion',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 3, 19, 43, 583396)),
        ),
        migrations.AlterField(
            model_name='realquestioncomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 3, 19, 43, 585248)),
        ),
        migrations.AlterField(
            model_name='realquestioncomment',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 3, 19, 43, 585228)),
        ),
    ]
