# Generated by Django 2.2.1 on 2019-06-12 13:48

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passionProjectApp', '0007_auto_20190612_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='answer_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='answer_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 13, 48, 51, 5942)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 13, 48, 51, 5924)),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 13, 48, 51, 7806)),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 13, 48, 51, 7777)),
        ),
        migrations.AlterField(
            model_name='realquestion',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 13, 48, 51, 3413)),
        ),
        migrations.AlterField(
            model_name='realquestion',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 13, 48, 51, 3387)),
        ),
        migrations.AlterField(
            model_name='realquestioncomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 13, 48, 51, 5373)),
        ),
        migrations.AlterField(
            model_name='realquestioncomment',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 13, 48, 51, 5353)),
        ),
    ]
