# Generated by Django 2.0.6 on 2019-06-12 23:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('passionProjectApp', '0008_auto_20190612_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='anscom_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='anscom_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realquestioncomment',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='questcom_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realquestioncomment',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='questcom_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='realquestion',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='realquestion',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='realquestioncomment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='realquestioncomment',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
