# Generated by Django 2.0.6 on 2019-07-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passionProjectApp', '0011_realquestion_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realquestion',
            old_name='tag',
            new_name='topic',
        ),
    ]
